# Generated by Django 3.2.9 on 2022-01-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedica', '0005_paciente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='documento',
            field=models.IntegerField(default=8),
        ),
    ]
