# Generated by Django 3.2.9 on 2022-01-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedica', '0011_alter_paciente_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='documento',
            new_name='dni',
        ),
    ]
