# Generated by Django 3.2.9 on 2022-01-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedica', '0012_rename_documento_paciente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(blank=True),
        ),
    ]
