# Generated by Django 3.2.9 on 2022-01-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedica', '0014_alter_paciente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(max_length=20),
        ),
    ]
